#!/bin/bash
MSG_FILE=$1
FILE_CONTENT="$(cat $MSG_FILE)"
# Initialize constants here
export REGEX='^([0-9]{4} : )'
export ERROR_MSG="Commit message format must be *Ticket : (message)*"
if [[ $FILE_CONTENT =~ $REGEX ]]; then
 echo "Good commit!"
else
  echo "Bad commit \"$FILE_CONTENT\""
 echo $ERROR_MSG
 exit 1
fi
exit 0